### ISSUE TITLE
Error and stuck trying to load into story mode

### ISSUE THREAD

**Issue by narkafh** [jalil49/Cosplay-Academy#2]
When I load my save my log gets filled with the following exception:

```
NullReferenceException: Object reference not set to an instance of an object
  at KKAPI.Chara.CharacterApi+<>c__DisplayClass16_0.<CreateOrAddBehaviours>b__0 (Unit _) [0x00000] in <filename unknown>:0 
  at UniRx.Observer+Subscribe`1[UniRx.Unit].OnNext (Unit value) [0x00000] in <filename unknown>:0 
  at UniRx.Subject`1[UniRx.Unit].OnNext (Unit value) [0x00000] in <filename unknown>:0 
  at UniRx.Triggers.ObservableUpdateTrigger.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

When I click next, there's the short conversation with a random classmate and then it gets stuck trying to load into school.

Here's my full output log:

[output_log.txt](https://github.com/jalil49/Cosplay-Academy/files/6933980/output_log.txt)

Line 1579 is when the exception spam starts when I load my save. Lines 16700-18650 have some different exceptions which I think occurred when I clicked next. Then the same exception from before starts spamming again.

I'm using KKAPI 1.20.3 and BepInEx 5.4.11.0. I'm using kPlug as well, but from what I read in your readme, it sounded like it should mostly work with it. I also have Pregnancy and PregnancyPlus installed. I saw some exceptions in the log about PregnancyPlus that might be related.

**Comment by jalil49** [comment]
I am seeing an error related to Cosplay Academy as it claims the dll failed to load (not sure why), but doesn't seem to be caused directly by cosplay academy, asked the chika bot on the Koikatsu Discord by posting your output log in the Help discord and it pointed out that a lot of plugins you got are old. 

> "• Your mods folder looks to be very messy and there are many duplicate mods. This can cause issues, please consider cleaning it up.
• The following files failed to load: Cosplay Academy.dll
Some of these files are missing, corrupted or duplicated, which can cause other files to fail to load as well. This can cause plugins or even the game itself to crash or misbehave.
• A lot of plugins are old, updating them might fix some issues. You can use HF Patch to update everything: https://github.com/ManlyMarco/KK-HF_Patch/releases/latest
• It looks like something in your game is crashing on every frame. This can drastically reduce FPS and/or introduce stuttering/lag. This is usually caused by outdated or incompatible plugins/mods, and in rare cases by corrupted game files."

**Comment by jalil49** [comment]
What version of HF patch are you running if at all?

**Comment by narkafh** [comment]
I think I'm using 3.1. I've been manually adding things in since then. I've been worried about the patch breaking anything, but I'll make a backup and try that. Thanks.

**Comment by jalil49** [comment]
The only thing i can think breaking is Kplug since supposedly doesn't cooperate or something as he keeps his stuff locked away including source code.
haven't messed with it since the 2.5 code i got to make cosplay mode work with outfits in subfolders.

**Comment by jalil49** [comment]
Realized it might be related to a missing reference possible solved with latest update as I removed unnecessary references
